### PR TITLE
Only use setRawMode when it exists

### PR DESCRIPTION
**Pull request by krl**
This bit me when using the script inside an electron app.

some discussion:
https://github.com/joyent/node/issues/8204

### CODE REVIEW

**Comment by rynti** [comment]
Looks good, thanks for your contribution! :)

**Comment by krl** [comment]
Awesome, could you also publish the new version to npm?

**Comment by rynti** [comment]
Sure, will do it as soon as I get a chance for it, probably later today or tomorrow.

**Comment by krl** [comment]
@rynti reminder on npm, i'm using shutdown-handler-krlpatch in a project now and it would be nice to get rid of that :)

**Comment by rynti** [comment]
@krl Sorry for the delay, updated it now (https://www.npmjs.com/package/shutdown-handler is now on version 1.0.1)

**Comment by krl** [comment]
great, thank you! :+1:

**Pull request merged**
